# Generated by Django 5.1.4 on 2025-02-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_text',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='order_text',
            old_name='order_id',
            new_name='order',
        ),
    ]
